services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    ports:
     - 8000:80 #map any custom port to use (replace 8000 not 80, 9445 is the default)
    volumes:
     - ./bitwarden:/data:rw
    environment:
#     - ROCKET_TLS={certs="/ssl/certs/certs.pem",key="/ssl/private/key.pem"}  // Environment variable is specific to the Rocket web server
#     - ADMIN_TOKEN={longpasswordofyourchoosing}
     - WEBSOCKET_ENABLED=true
     - SIGNUPS_ALLOWED=false
#     - DOMAIN=${DOMAIN} (This is taken care of by our Caddyfile.)

# Next time I build out a homelab, I would segment it out using these options.
#networks:
#  default:
#    external:
#      name: nginx-proxy-network
